name: sentiment-trading-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pip
  - pip:
      - praw
      - pymongo 
  - nltk 
  - yfinance 
  - gymnasium
  - matplotlib 